baseURL = "https://yentsaidev.com/"
languageCode = "zh-tw"
title = "Yen Tsai dev"
theme = "PaperMod"
[pagination]
  pagerSize = 10

[params]
  author = "Yen Tsai"
  description = "後端工程師 | 喜歡 Vue、區塊鏈、健身與美食"
  keywords = ["後端", "Vue", "區塊鏈", "健身", "個人網站"]

  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowAuthor = true

  [params.profileMode]
    enabled = true
    title = "Yen Tsai"
    subtitle = "Backend Engineer, passionate about sharing technology and life experiences."
    imageUrl = "https://avatars.githubusercontent.com/u/22338002?v=4"
    math = true
    
    [[params.profileMode.buttons]]
      name = "Project"
      url = "/project"

    [[params.profileMode.buttons]]
      name = "About Me"
      url = "/experience"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yanzzzzzzzzz"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jack-tsai-1033721a5/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"

[menu]

  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 1

  [[menu.main]]
    identifier = "project"
    name = "Project"
    url = "/project/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3
